version: '2'
services:
  pg:
    image: postgres:9.3
    
  conjur:
    image: cyberark/conjur
    command: server -a cucumber
    environment:
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_DATA_KEY:

  cli:
    build:
      dockerfile: Dockerfile.standalone
      context: ..
    entrypoint: sleep
    command: infinity
    environment:
      RAILS_ENV: development
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber
    working_dir: /src/conjur-cli
    volumes:
    - ..:/src/conjur-cli
