pg:
  image: postgres:9.3
  
possum:
  image: possum
  command: server -a cucumber
  environment:
    DATABASE_URL: postgres://postgres@pg/postgres
    POSSUM_DATA_KEY:
  links:
  - pg:pg

cli:
  image: ruby:2.3
  entrypoint: sleep
  command: infinity
  environment:
    CONJUR_APPLIANCE_URL: http://possum
    CONJUR_ACCOUNT: cucumber
  volumes:
  - ..:/src/conjur-cli
  links:
  - possum:possum
